path_to_boost=../boost_dir
all:
	g++ segment.cpp utils.cpp quadrilater.cpp periodic.cpp prescribed.cpp reflective.cpp periodic_bdrs.cpp prescribed_bdrs.cpp reflective_bdrs.cpp materials.cpp particle.cpp sources.cpp initial.cpp volumetric.cpp body_force.cpp adjoint_detectors.cpp detector_T.cpp detector_H.cpp detector_array_T.cpp detector_array_H.cpp plot_utils.cpp main.cpp  -I ${path_to_boost} -o MC.out
